### ISSUE TITLE
class stripped from the parent element

### ISSUE THREAD

**Issue by chrisbell08** [lmiller1990/v-switch-case#1]
in the following example:

     <div v-switch="validateUrl" class="validateUrl">
                <p v-case="'validating'">Checking Url...</p>
                <p v-case="'validated'">Valid <Icon name="check"/></p>
                <p v-case="''">-</p>
            </div>

the validate url class is stripped from the div

**Comment by lmiller1990** [comment]
Odd. Thanks for the issue, this library is still in it's (very) early days. 

I'll take a look at this tonight.

**Comment by lmiller1990** [comment]
@chrisbell08 This does not appear to be the case:

![image](https://user-images.githubusercontent.com/19196536/39989602-5a2a2808-57a5-11e8-8c2f-28cc44891534.png)

Can you post the entire code (or the minimum amount to recreate it?)

**Comment by lmiller1990** [comment]
@chrisbell08 Any luck on this?

**Comment by chrisbell08** [comment]
I must have been doing something wrong as it seems to be working fine now :)

**Comment by lmiller1990** [comment]
awesome. I released 1.0 recently with `v-default`, you can get it with `npm install v-switch-case@latest`.

I'll close this since it seems to be working okay, let me know if you have any other suggestions or feedback.
